# This is the configuration file for the program.
# The guide is on Github under Readme
# things with # infront is just a comment

# You can optionally specify custom activation profiles here. 
# Any you specify here that have the same name as in pishock_config.yaml
# will take precedence over the ones in pishock_config.yaml.
activation_profiles:
  Activation_1:
    mode: 0
    intensity: 100
    duration: 1000

# archipelago important variables (change only the values after the colon :)
archipelago:
  server: archipelago.gg
  room_code: 12345
  name: ArchipelagoName
  game: GameName
  password: null

# Deathlink settings
deathlink:
  activated: false
  devices: []

# Trap Link settings
trapLink:
  activated: false
  devices: []

# Archipelago Item/Trap Check Configuration
traps:
  trap-1:
    name: Item_check_name
    for_self: true
    devices: []
  trap-2:
    names:
      - Item_check_name_2
      - Item_check_name_3
    for_self: true
    devices: []

# All other items that comes from or goes to you
OtherChecks:
  activated: false
  send/receive: all                      
  devices: []
